--- 
javascripts: 
- admin:
  - jquery
  - jquery-ui-1.8.21.custom.min
  - jrails
  - jquery.fancybox
  - jquery.editinplace
  - jquery.qtip
  - jquery.scrollTo
  - jquery.timers
  - jquery.treeview
  - interface
  - dragdroptree
  - jquery.ajaxmanager  
  - admin
stylesheets: 
- admin:
  - admin
  - jquery.fancybox
  - jquery.qtip
  - ui-lightness/jquery-ui-1.8.4.custom
  - jquery-ui-1.8.17.custom/smoothness/jquery-ui-1.8.17.custom
  - uploadify
  - jquery.treeview
  - dragdroptree
