production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: your_database
  pool: 5
  username: your_username
  password: your_password
  host: localhost

development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: your_database
  pool: 5
  username: your_username
  password: your_password
  host: localhost


  


